import type { TimeClass } from '../types';
import type { PlayerAggregate } from './playerReport';
import baselinesJson from './baselines.generated.json';

/**
 * Rating-cohort baselines: per (time class, rating band) distributions of the
 * player-level metrics, measured with OUR engine at OUR depth (match rates are
 * engine- and depth-relative, so published numbers don't transfer).
 * Generated by tools/calibrate; see meta for provenance.
 */

export interface MetricBaseline {
  mean: number;
  std: number;
}

export interface BandBaseline {
  timeClass: TimeClass;
  minRating: number;
  /** exclusive */
  maxRating: number;
  nPlayers: number;
  t1Rate: MetricBaseline;
  t2Rate: MetricBaseline;
  t3Rate: MetricBaseline;
  acpl: MetricBaseline;
  accuracy: MetricBaseline;
  instantRate: MetricBaseline;
  thinkCv: MetricBaseline;
  /** spread of per-game accuracy within a player (optional: measured since v2 runs) */
  accuracyStd?: MetricBaseline;
  /** Spearman corr(think time, PV gap) — humans negative (optional: measured since v2 runs) */
  timeComplexityCorr?: MetricBaseline;
}

export interface BaselineTable {
  meta: {
    engine: string;
    depth: number;
    multiPv: number;
    generatedAt: string;
    /** true while the table comes from a small pilot run */
    pilot?: boolean;
  };
  bands: BandBaseline[];
}

/** bands thinner than this are shown, but marked provisional */
export const MIN_BAND_PLAYERS = 20;

/** composite-z tier thresholds */
export const UNUSUAL_Z = 2;
export const EXTREME_Z = 3.5;

export const defaultBaselines = baselinesJson as BaselineTable;

export function findBand(
  table: BaselineTable,
  timeClass: TimeClass,
  rating: number,
): BandBaseline | undefined {
  return table.bands.find(
    (band) => band.timeClass === timeClass && rating >= band.minRating && rating < band.maxRating,
  );
}

export type CohortTier = 'normal' | 'unusual' | 'extreme';

export interface CohortComparison {
  band: BandBaseline;
  provisional: boolean;
  /** z-scores oriented so that POSITIVE means "more engine-like than the cohort" */
  zT1?: number;
  zAcpl?: number;
  zAccuracy?: number;
  zInstant?: number;
  zThinkCv?: number;
  /** too-steady game-to-game accuracy (one-sided) */
  zConsistency?: number;
  composite: number;
  tier: CohortTier;
}

const MIN_STD = 1e-6;

function z(
  value: number | undefined,
  baseline: MetricBaseline | undefined,
  invert = false,
): number | undefined {
  if (value === undefined || baseline === undefined || baseline.std < MIN_STD) return undefined;
  const score = (value - baseline.mean) / baseline.std;
  return invert ? -score : score;
}

/**
 * Compares a player's aggregate to their rating cohort. The composite combines
 * the available z-scores with Stouffer's weighted method — Σ(w·z)/√Σw² — so
 * independent anomalies accumulate instead of averaging out. Engine-agreement
 * and mistake profile carry most of the weight; timing signals stay secondary
 * (they are noisier and honest fast players exist).
 */
export function compareToCohort(
  aggregate: PlayerAggregate,
  player: { timeClass: TimeClass; rating: number },
  table: BaselineTable = defaultBaselines,
): CohortComparison | undefined {
  const band = findBand(table, player.timeClass, player.rating);
  if (!band) return undefined;

  const zT1 = z(aggregate.t1.rate, band.t1Rate);
  const zAcpl = z(aggregate.acpl?.mean, band.acpl, true); // lower acpl = more suspicious
  const zAccuracy = z(aggregate.accuracyMean?.mean, band.accuracy);
  // timing signals are ONE-SIDED: flat timing / instant replies add suspicion,
  // but varied timing must not subtract it — assistance can fake thinking time
  const clampSuspicion = (score: number | undefined) =>
    score === undefined ? undefined : Math.max(0, score);
  const zInstant = clampSuspicion(z(aggregate.timing?.instantRate, band.instantRate));
  const zThinkCv = clampSuspicion(
    z(aggregate.timing?.coefficientOfVariation, band.thinkCv, true), // flatter = more suspicious
  );
  // steadier-than-human game-to-game accuracy (lower spread = more suspicious)
  const zConsistency = clampSuspicion(z(aggregate.accuracyStd?.value, band.accuracyStd, true));
  // NOTE: time-vs-difficulty correlation is measured (aggregate.timeComplexityCorr)
  // but deliberately NOT scored: calibration showed honest players average ≈ 0.00
  // on it too (the PV1−PV2 gap is a weak difficulty proxy), so it cannot
  // discriminate. Revisit with a better difficulty measure.

  const weighted: [number | undefined, number][] = [
    [zT1, 0.3],
    [zAcpl, 0.3],
    [zAccuracy, 0.15],
    [zConsistency, 0.1],
    [zInstant, 0.025],
    [zThinkCv, 0.025],
  ];
  let numerator = 0;
  let squaredWeights = 0;
  for (const [score, weight] of weighted) {
    if (score === undefined) continue;
    numerator += score * weight;
    squaredWeights += weight * weight;
  }
  if (squaredWeights === 0) return undefined;
  const composite = numerator / Math.sqrt(squaredWeights);

  return {
    band,
    provisional: band.nPlayers < MIN_BAND_PLAYERS || table.meta.pilot === true,
    zT1,
    zAcpl,
    zAccuracy,
    zInstant,
    zThinkCv,
    zConsistency,
    composite,
    tier: composite >= EXTREME_Z ? 'extreme' : composite >= UNUSUAL_Z ? 'unusual' : 'normal',
  };
}
