import type { Platform, TimeClass } from '../types';
import type { PlayerAggregate } from './playerReport';
import baselinesJson from './baselines.generated.json';

/**
 * Rating-conditioned baselines: a per-(platform, time class) GRID of rating
 * points, each holding the distribution of a metric over real players within
 * ±window of that rating (measured with OUR engine at OUR depth, match rates are
 * engine- and depth-relative, so published numbers don't transfer). Per-platform
 * because chess.com and lichess ratings are not the same scale. compareToCohort()
 * interpolates the grid to a player's EXACT rating on their platform, so a
 * strong-for-their-band player is judged against their real neighborhood.
 * Generated by tools/calibrate.
 */

export interface MetricBaseline {
  mean: number;
  std: number;
}

/** metric distributions over players within ±window of `rating` */
export interface RatingGridPoint {
  rating: number;
  nPlayers: number;
  t1Rate: MetricBaseline;
  t2Rate: MetricBaseline;
  t3Rate: MetricBaseline;
  acpl: MetricBaseline;
  accuracy: MetricBaseline;
  instantRate: MetricBaseline;
  thinkCv: MetricBaseline;
  accuracyStd?: MetricBaseline;
  timeComplexityCorr?: MetricBaseline;
}

export interface BaselineTable {
  meta: {
    engine: string;
    depth: number;
    multiPv: number;
    generatedAt: string;
    /** true while the table comes from a small pilot run */
    pilot?: boolean;
    /** neighborhood half-width each grid point summarizes */
    window: number;
    step: number;
  };
  /** grid points per platform then time class, ascending by rating */
  grid: Partial<Record<Platform, Partial<Record<TimeClass, RatingGridPoint[]>>>>;
}

/**
 * The cohort a single player is judged against: same shape the report renders,
 * but interpolated to the player's exact rating. minRating/maxRating describe
 * the ±window neighborhood it summarizes (for the "players rated X-Y" copy).
 */
export interface BandBaseline {
  timeClass: TimeClass;
  minRating: number;
  maxRating: number;
  nPlayers: number;
  t1Rate: MetricBaseline;
  t2Rate: MetricBaseline;
  t3Rate: MetricBaseline;
  acpl: MetricBaseline;
  accuracy: MetricBaseline;
  instantRate: MetricBaseline;
  thinkCv: MetricBaseline;
  accuracyStd?: MetricBaseline;
  timeComplexityCorr?: MetricBaseline;
}

/** below this many players in the local neighborhood, the report is provisional */
export const MIN_BAND_PLAYERS = 20;

/** composite-z tier thresholds */
export const UNUSUAL_Z = 2;
export const EXTREME_Z = 3.5;

export const defaultBaselines = baselinesJson as BaselineTable;

const lerp = (a: number, b: number, t: number): number => a + (b - a) * t;
function lerpMetric(
  a: MetricBaseline | undefined,
  b: MetricBaseline | undefined,
  t: number,
): MetricBaseline | undefined {
  if (!a) return b;
  if (!b) return a;
  return { mean: lerp(a.mean, b.mean, t), std: lerp(a.std, b.std, t) };
}

/**
 * Interpolates the grid to a player's exact rating on their platform, returning
 * the cohort to judge them against. Below/above the measured range it clamps to
 * the nearest endpoint. Returns undefined when that platform + time class has no grid.
 */
export function cohortAt(
  table: BaselineTable,
  platform: Platform,
  timeClass: TimeClass,
  rating: number,
): BandBaseline | undefined {
  const pts = table.grid[platform]?.[timeClass];
  if (!pts || pts.length === 0) return undefined;
  let lo = pts[0]!;
  let hi = pts[pts.length - 1]!;
  if (rating <= lo.rating) hi = lo;
  else if (rating >= hi.rating) lo = hi;
  else {
    for (let i = 0; i < pts.length - 1; i++) {
      if (rating >= pts[i]!.rating && rating <= pts[i + 1]!.rating) {
        lo = pts[i]!;
        hi = pts[i + 1]!;
        break;
      }
    }
  }
  const t = hi.rating === lo.rating ? 0 : (rating - lo.rating) / (hi.rating - lo.rating);
  const w = table.meta.window;
  return {
    timeClass,
    minRating: Math.round(rating - w),
    maxRating: Math.round(rating + w),
    nPlayers: Math.round(lerp(lo.nPlayers, hi.nPlayers, t)),
    t1Rate: lerpMetric(lo.t1Rate, hi.t1Rate, t)!,
    t2Rate: lerpMetric(lo.t2Rate, hi.t2Rate, t)!,
    t3Rate: lerpMetric(lo.t3Rate, hi.t3Rate, t)!,
    acpl: lerpMetric(lo.acpl, hi.acpl, t)!,
    accuracy: lerpMetric(lo.accuracy, hi.accuracy, t)!,
    instantRate: lerpMetric(lo.instantRate, hi.instantRate, t)!,
    thinkCv: lerpMetric(lo.thinkCv, hi.thinkCv, t)!,
    accuracyStd: lerpMetric(lo.accuracyStd, hi.accuracyStd, t),
    timeComplexityCorr: lerpMetric(lo.timeComplexityCorr, hi.timeComplexityCorr, t),
  };
}

export type CohortTier = 'normal' | 'unusual' | 'extreme';

export interface CohortComparison {
  band: BandBaseline;
  provisional: boolean;
  /** z-scores oriented so that POSITIVE means "more engine-like than the cohort" */
  zT1?: number;
  zAcpl?: number;
  zAccuracy?: number;
  zInstant?: number;
  zThinkCv?: number;
  /** too-steady game-to-game accuracy (one-sided) */
  zConsistency?: number;
  composite: number;
  tier: CohortTier;
}

const MIN_STD = 1e-6;

function z(
  value: number | undefined,
  baseline: MetricBaseline | undefined,
  invert = false,
): number | undefined {
  if (value === undefined || baseline === undefined || baseline.std < MIN_STD) return undefined;
  const score = (value - baseline.mean) / baseline.std;
  return invert ? -score : score;
}

/**
 * Compares a player's aggregate to the cohort at their exact rating on their
 * platform. The composite combines the available z-scores with Stouffer's
 * weighted method (Σ(w·z)/√Σw²) so independent anomalies accumulate instead of
 * averaging out. Engine-agreement and mistake profile carry most of the weight;
 * timing signals stay secondary (they are noisier and honest fast players exist).
 */
export function compareToCohort(
  aggregate: PlayerAggregate,
  player: { platform: Platform; timeClass: TimeClass; rating: number },
  table: BaselineTable = defaultBaselines,
): CohortComparison | undefined {
  const band = cohortAt(table, player.platform, player.timeClass, player.rating);
  if (!band) return undefined;

  const zT1 = z(aggregate.t1.rate, band.t1Rate);
  const zAcpl = z(aggregate.acpl?.mean, band.acpl, true); // lower acpl = more suspicious
  const zAccuracy = z(aggregate.accuracyMean?.mean, band.accuracy);
  // timing signals are ONE-SIDED: flat timing / instant replies add suspicion,
  // but varied timing must not subtract it, assistance can fake thinking time
  const clampSuspicion = (score: number | undefined) =>
    score === undefined ? undefined : Math.max(0, score);
  const zInstant = clampSuspicion(z(aggregate.timing?.instantRate, band.instantRate));
  const zThinkCv = clampSuspicion(
    z(aggregate.timing?.coefficientOfVariation, band.thinkCv, true), // flatter = more suspicious
  );
  // steadier-than-human game-to-game accuracy (lower spread = more suspicious)
  const zConsistency = clampSuspicion(z(aggregate.accuracyStd?.value, band.accuracyStd, true));

  const weighted: [number | undefined, number][] = [
    [zT1, 0.3],
    [zAcpl, 0.3],
    [zAccuracy, 0.15],
    [zConsistency, 0.1],
    [zInstant, 0.025],
    [zThinkCv, 0.025],
  ];
  let numerator = 0;
  let squaredWeights = 0;
  for (const [score, weight] of weighted) {
    if (score === undefined) continue;
    numerator += score * weight;
    squaredWeights += weight * weight;
  }
  if (squaredWeights === 0) return undefined;
  const composite = numerator / Math.sqrt(squaredWeights);

  return {
    band,
    provisional: band.nPlayers < MIN_BAND_PLAYERS || table.meta.pilot === true,
    zT1,
    zAcpl,
    zAccuracy,
    zInstant,
    zThinkCv,
    zConsistency,
    composite,
    tier: composite >= EXTREME_Z ? 'extreme' : composite >= UNUSUAL_Z ? 'unusual' : 'normal',
  };
}
